name: pure_live
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dpad: ^3.0.0
  dio: ^5.9.2
  pretty_dio_logger: ^1.4.0
  infinite_scroll_pagination: ^5.1.1
  easy_refresh: ^3.5.1
  cached_network_image: ^3.4.1
  go_router: ^17.3.0
  go_transitions: ^0.8.3
  hive_ce: ^2.15.1 # Hive本地数据库
  hive_ce_flutter: ^2.3.3 # Hive Flutter集成
  logger: ^2.7.0
  media_kit: ^1.2.6 # Primary package.
  media_kit_video: ^2.0.1 # For video rendering.
  media_kit_libs_video: ^1.0.7 # Native video dependencies.
  flutter_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3
  freezed_annotation: ^3.1.0
  flutter_smart_dialog: ^5.1.0
  path: ^1.9.1
  json_annotation: ^4.12.0
  retrofit: ^4.9.2
  connectivity_plus: ^7.1.1
  device_info_plus: ^13.1.0
  package_info_plus: ^10.1.0
  collection: ^1.19.1
  path_provider: ^2.1.6
  flutter_animate: ^4.5.2
  rxdart: ^0.28.0
  flutter_cache_manager: ^3.4.1
  hexcolor: ^3.1.3
  flutter_screenutil_plus: ^1.5.0
  intl: ^0.20.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.5
  build_runner: ^2.15.0
  go_router_builder: ^4.3.0
  riverpod_generator: ^4.0.4
  json_serializable: ^6.14.0
  retrofit_generator: ^10.2.7
  hive_ce_generator: ^1.11.2
flutter:
  uses-material-design: true
