import 'package:flutter/material.dart';
import 'package:remixicon/remixicon.dart';

/// One pickable icon: the icon itself plus a label used for the caption.
class IconOption {
  const IconOption(this.label, this.icon);

  final String label;
  final IconData icon;
}

/// Icons offered by the icon picker.
///
/// Two families are mixed on purpose: the Material set the app already uses for
/// player and platform rows, and the Remix line icons the desktop app uses for
/// its settings rows. The list is curated rather than "every icon in the
/// package" so a remote user can actually reach the one they want.
const List<IconOption> kIconCatalog = <IconOption>[
  // Favourites, follow, status
  IconOption('heart_line', Remix.heart_3_line),
  IconOption('heart_fill', Remix.heart_3_fill),
  IconOption('star_line', Remix.star_line),
  IconOption('star_fill', Remix.star_fill),
  IconOption('bookmark_line', Remix.bookmark_line),
  IconOption('bookmark_fill', Remix.bookmark_fill),
  IconOption('fire_line', Remix.fire_line),
  IconOption('fire_fill', Remix.fire_fill),
  IconOption('thumb_up', Remix.thumb_up_line),
  IconOption('emotion', Remix.emotion_line),
  // Live, video, media
  IconOption('live', Remix.live_line),
  IconOption('tv', Remix.tv_line),
  IconOption('tv_2', Remix.tv_2_line),
  IconOption('film', Remix.film_line),
  IconOption('movie', Remix.movie_line),
  IconOption('play_circle', Remix.play_circle_line),
  IconOption('pause_circle', Remix.pause_circle_line),
  IconOption('video', Remix.video_line),
  IconOption('camera', Remix.camera_line),
  IconOption('image', Remix.image_line),
  IconOption('gallery', Remix.gallery_line),
  IconOption('music', Remix.music_2_line),
  IconOption('headphone', Remix.headphone_line),
  IconOption('volume_up', Remix.volume_up_line),
  IconOption('volume_mute', Remix.volume_mute_line),
  IconOption('mic', Remix.mic_line),
  IconOption('equalizer', Remix.equalizer_line),
  IconOption('picture_in_picture', Remix.picture_in_picture_2_line),
  IconOption('fullscreen', Remix.fullscreen_line),
  IconOption('aspect_ratio', Remix.aspect_ratio_line),
  IconOption('speed_up', Remix.speed_up_line),
  IconOption('hd', Remix.hd_line),
  IconOption('airplay', Remix.airplay_line),
  IconOption('cast', Remix.cast_line),
  IconOption('download', Remix.download_2_line),
  IconOption('upload', Remix.upload_2_line),
  IconOption('file_download', Remix.file_download_line),
  IconOption('file_upload', Remix.file_upload_line),
  // Navigation and layout
  IconOption('apps', Remix.apps_2_line),
  IconOption('app_store', Remix.apps_line),
  IconOption('grid', Remix.grid_line),
  IconOption('layout_grid', Remix.layout_grid_line),
  IconOption('dashboard', Remix.dashboard_2_line),
  IconOption('menu', Remix.menu_line),
  IconOption('sidebar', Remix.side_bar_line),
  IconOption('list', Remix.list_check),
  IconOption('pages', Remix.pages_line),
  IconOption('layout', Remix.layout_line),
  IconOption('drag', Remix.drag_move_line),
  IconOption('arrow_left_right', Remix.arrow_left_right_line),
  IconOption('arrow_up_down', Remix.arrow_up_down_line),
  IconOption('expand', Remix.expand_height_line),
  IconOption('collapse', Remix.collapse_diagonal_line),
  // Categories, tags, discovery
  IconOption('apps_category', Remix.apps_2_fill),
  IconOption('price_tag', Remix.price_tag_3_line),
  IconOption('tag', Remix.hashtag),
  IconOption('compass', Remix.compass_3_line),
  IconOption('compass_discover', Remix.compass_discover_line),
  IconOption('search', Remix.search_line),
  IconOption('filter', Remix.filter_2_line),
  IconOption('sort', Remix.sort_asc),
  IconOption('global', Remix.global_line),
  IconOption('earth', Remix.earth_line),
  IconOption('map_pin', Remix.map_pin_line),
  IconOption('links', Remix.links_line),
  // People, accounts, interaction
  IconOption('account', Remix.account_circle_line),
  IconOption('user', Remix.user_3_line),
  IconOption('group', Remix.group_line),
  IconOption('team', Remix.team_line),
  IconOption('vip', Remix.vip_crown_line),
  IconOption('trophy', Remix.trophy_line),
  IconOption('medal', Remix.medal_line),
  IconOption('gift', Remix.gift_line),
  IconOption('coin', Remix.copper_coin_line),
  IconOption('wallet', Remix.wallet_3_line),
  IconOption('shield_user', Remix.shield_user_line),
  IconOption('chat', Remix.chat_3_line),
  IconOption('chat_settings', Remix.chat_settings_line),
  IconOption('comment', Remix.chat_smile_2_line),
  // Appearance and text
  IconOption('palette', Remix.palette_line),
  IconOption('brush', Remix.brush_line),
  IconOption('magic', Remix.magic_line),
  IconOption('moon', Remix.moon_clear_line),
  IconOption('sun', Remix.sun_line),
  IconOption('blur', Remix.blur_off_line),
  IconOption('contrast', Remix.contrast_drop_line),
  IconOption('font_color', Remix.font_color),
  IconOption('font_size', Remix.font_size),
  IconOption('text', Remix.text),
  IconOption('translate', Remix.translate_2),
  IconOption('bold', Remix.bold),
  IconOption('loader', Remix.loader_4_line),
  // Player, performance and system
  IconOption('cpu', Remix.cpu_line),
  IconOption('memory', Remix.device_line),
  IconOption('toggle', Remix.toggle_line),
  IconOption('settings', Remix.settings_4_line),
  IconOption('settings_5', Remix.settings_5_line),
  IconOption('tune', Remix.equalizer_2_line),
  IconOption('refresh', Remix.refresh_line),
  IconOption('restart', Remix.restart_line),
  IconOption('power', Remix.shut_down_line),
  IconOption('timer', Remix.timer_line),
  IconOption('time', Remix.time_line),
  IconOption('history', Remix.history_line),
  IconOption('calendar', Remix.calendar_line),
  IconOption('speed', Remix.dashboard_3_line),
  IconOption('signal', Remix.signal_tower_line),
  IconOption('wifi', Remix.wifi_line),
  IconOption('server', Remix.server_line),
  IconOption('database', Remix.database_2_line),
  IconOption('cloud', Remix.cloud_line),
  IconOption('folder', Remix.folder_open_line),
  IconOption('file_text', Remix.file_text_line),
  IconOption('file_add', Remix.file_add_line),
  IconOption('delete_bin', Remix.delete_bin_6_line),
  IconOption('lock', Remix.lock_line),
  IconOption('shield', Remix.shield_check_line),
  IconOption('bug', Remix.bug_line),
  IconOption('rocket', Remix.rocket_2_line),
  IconOption('flashlight', Remix.flashlight_line),
  IconOption('lightbulb', Remix.lightbulb_line),
  IconOption('information', Remix.information_line),
  IconOption('question', Remix.question_line),
  IconOption('error_warning', Remix.error_warning_line),
  IconOption('github', Remix.github_line),
  IconOption('android', Remix.android_line),
  IconOption('windows', Remix.windows_line),
  // Material icons used by player rows
  IconOption('extension', Icons.extension_rounded),
  IconOption('sports_esports', Icons.sports_esports_rounded),
  IconOption('celebration', Icons.celebration_rounded),
  IconOption('military_tech', Icons.military_tech_rounded),
  IconOption('workspace_premium', Icons.workspace_premium_rounded),
  IconOption('insights', Icons.insights_rounded),
  IconOption('groups', Icons.groups_2_rounded),
  IconOption('toll', Icons.toll_rounded),
  IconOption('theaters', Icons.theaters_rounded),
  IconOption('smart_display', Icons.smart_display_rounded),
  IconOption('sensors', Icons.sensors_rounded),
  IconOption('bolt', Icons.bolt_rounded),
  IconOption('explore', Icons.explore_rounded),
  IconOption('auto_awesome', Icons.auto_awesome_rounded),
  IconOption('interests', Icons.interests_rounded),
  IconOption('view_comfy', Icons.view_comfy_rounded),
  IconOption('view_module', Icons.view_module_rounded),
  IconOption('collections_bookmark', Icons.collections_bookmark_outlined),
  IconOption('category', Icons.category_rounded),
  IconOption('local_fire', Icons.local_fire_department_outlined),
  IconOption('live_tv', Icons.live_tv_rounded),
  IconOption('devices', Icons.devices_rounded),
  IconOption('settings_remote', Icons.settings_remote_rounded),
];
